### ISSUE TITLE
能否加入下拉刷新与上拉加载更多只能一个并存

### ISSUE THREAD

**Issue by chenwulue** [Chanven/CommonPullToRefresh#17]
当在上拉加载更多即isLoading为true的过程中，让swiperefreshlayout的enable为false，直到loadMoreComplete被调用，同样是下拉刷新过程中，上拉加载更多也设置为不可用

**Comment by Chanven** [comment]
compile 1.1.0
调用`setLoadMoreEnable(false)`禁用
