### ISSUE TITLE
LoadMoreComplete方法没有判空操作。。

### ISSUE THREAD

**Issue by wenkchan** [Chanven/CommonPullToRefresh#20]

**Comment by developer-shiyan** [comment]
什么意思，请具体描述问题!

**Comment by wenkchan** [comment]
就在这个方法里面，你看一下，没有对那个footerview进行判空操作，另外- -。怎么去掉这个footerview，就我用的时候，在数据加载到第二页以上的时候，如果获取失败，清空listview，然后这个footview还是存在。。

**Comment by cccfly-bake** [comment]
有listview有一个setempty的方法可以设置适配器没有数据时候的情况，但是和SwipeRefreshLayout使用会有冲突，我现在也对这个很困惑， 也想移除一下footer，因为没有数据的时候footer就在最上面显示着，太尴尬了

**Comment by Chanven** [comment]
调用setLoadMoreEnable(false)，移除footer，禁用加载更多
需要compile 1.1.0版本
