### ISSUE TITLE
如何设置上拉加载的样式

### ISSUE THREAD

**Issue by Kilnn** [Chanven/CommonPullToRefresh#7]
我需要修改上拉加载的样式,但是找不到地方设置.
在PtrFrameLayout中已经被写死了

```
private ILoadViewMoreFactory loadViewFactory = new DefaultLoadMoreFooter();  //line 1046
```

**Comment by Chanven** [comment]
很久没更新，抱歉，已经上传了1.1.0
[https://github.com/Chanven/CommonPullToRefresh#headerfooter样式](url)
