### ISSUE TITLE
recyclerview-v7:23.2.1以上,autoMeasure导致的FooterView满屏的问题

### ISSUE THREAD

**Issue by Kilnn** [Chanven/CommonPullToRefresh#8]
最新的recyclerview加了autoMeasure功能,在 RecyclerAdapterWithHF 中的onCreateViewHolder里面,
自己创建的HeaderFooterView不应该在用MATCH_PARENT了.

`FrameLayout frameLayout = new FrameLayout(viewGroup.getContext());
            // make sure it fills the space
            frameLayout.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));
            return new HeaderFooterViewHolder(frameLayout);`

**Comment by addappcn** [comment]
哥们你改了可以提交啊

**Comment by chenwulue** [comment]
哥们你改了后我可以compile啊

**Comment by excellenttank** [comment]
哥们你还好了就提交一下呗

**Comment by Kilnn** [comment]
提交了别人也不一定合进去啊，这个项目已经停止维护了吧，很久都没更新了。
